version: "3.1"

services:

  mysql:
    image: mysql:5.6
    container_name: cargocorp-mysql
    working_dir: /app
    volumes:
      - .:/app
      - ./data/mysql_db:/var/lib/mysql
    env_file:
      - app.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"

  web:
    depends_on:
      - mysql
    build: .
    container_name: cargocorp-web
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    env_file:
      - app.env
    ports:
      - "4080:80"


